import '../styles/globals.css';
import Navbar from '../component/Navbar';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <div className='py-24 px-12 lg:px-48'>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
